### ISSUE TITLE
Sticky headers [Feature Request]

### ISSUE THREAD

**Issue by majid701** [ssseasonnn/Yasha#8]
Great library! I love it reduces quiet a lot the boilerplate needed.
The only thing thats missing is the possibility to add sticky headers (sections). 
Any suggestions on how it could be implemented? 

thanks

**Comment by ssseasonnn** [comment]
Sorry to reply so late,I found this may help you. [Stick header for recyclerview](https://medium.com/@saber.solooki/sticky-header-for-recyclerview-c0eb551c3f68)
